FROM rust:1.39 as builder
WORKDIR /usr/src/myapp
COPY ..
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y libssl
COPY --from-builder /usr/src/myapp /usr/local/bin/myapp
CMD ["myapp]